import type { LLMProviderType } from "./types";

export type ProviderCompatibility = "openai" | "anthropic";

export interface ProviderCatalogEntry {
  id: LLMProviderType;
  name: string;
  compatibility: ProviderCompatibility;
  baseUrl?: string;
  defaultModel: string;
  knownModels?: string[];
  apiKeyLabel: string;
  apiKeyPlaceholder?: string;
  apiKeyUrl?: string;
  requiresBaseUrl?: boolean;
  apiKeyOptional?: boolean;
  description?: string;
}

export const CUSTOM_PROVIDER_CATALOG: ProviderCatalogEntry[] = [
  {
    id: "opencode",
    name: "OpenCode Zen",
    compatibility: "openai",
    baseUrl: "https://opencode.ai/zen/v1",
    defaultModel: "gpt-5.5",
    knownModels: [
      "gpt-5.6-sol",
      "gpt-5.6-terra",
      "gpt-5.6-luna",
      "gpt-5.5",
      "gpt-5.4",
      "gpt-5.4-mini",
      "gpt-5.3-codex",
      "grok-4.6",
      "grok-4.5",
      "claude-sonnet-4-6",
      "claude-opus-4-6",
      "qwen3.7-max",
      "qwen3.7-plus",
      "qwen3.6-plus",
      "deepseek-v4-pro",
      "deepseek-v4-flash",
      "minimax-m3",
      "glm-5.2",
      "kimi-k3",
    ],
    apiKeyLabel: "API Key / Token",
    apiKeyPlaceholder: "Paste your OpenCode Zen API key",
    apiKeyUrl: "https://opencode.ai/auth",
    description: "Pay-as-you-go access to OpenCode's curated coding models.",
  },
  {
    id: "opencode-go",
    name: "OpenCode Go",
    compatibility: "openai",
    baseUrl: "https://opencode.ai/zen/go/v1",
    defaultModel: "qwen3.7-plus",
    knownModels: [
      "grok-4.5",
      "gpt-5.6-luna",
      "glm-5.3",
      "glm-5.2",
      "glm-5.1",
      "kimi-k3",
      "kimi-k2.7-code",
      "kimi-k2.6",
      "deepseek-v4-pro",
      "deepseek-v4-flash",
      "mimo-v2.5",
      "mimo-v2.5-pro",
      "minimax-m3",
      "minimax-m2.7",
      "qwen3.8-max",
      "qwen3.7-max",
      "qwen3.7-plus",
      "qwen3.6-plus",
      "hy3",
    ],
    apiKeyLabel: "API Key / Subscription Token",
    apiKeyPlaceholder: "Paste your OpenCode Go API key",
    apiKeyUrl: "https://opencode.ai/workspace",
    description: "Use your OpenCode Go subscription with the curated model lineup.",
  },
  {
    id: "google-vertex",
    name: "Google Vertex",
    compatibility: "openai",
    defaultModel: "gemini-2.0-flash",
    apiKeyLabel: "Access Token",
    apiKeyPlaceholder: "ya29...",
    requiresBaseUrl: true,
    description: "Requires a compatible gateway endpoint.",
  },
  {
    id: "google-antigravity",
    name: "Google Antigravity",
    compatibility: "openai",
    defaultModel: "gemini-2.0-flash",
    apiKeyLabel: "Access Token",
    apiKeyPlaceholder: "ya29...",
    requiresBaseUrl: true,
    description: "Requires a compatible gateway endpoint.",
  },
  {
    id: "google-gemini-cli",
    name: "Google Gemini CLI",
    compatibility: "openai",
    defaultModel: "gemini-2.0-flash",
    apiKeyLabel: "Access Token",
    apiKeyPlaceholder: "ya29...",
    requiresBaseUrl: true,
    description: "Requires a compatible gateway endpoint.",
  },
  {
    id: "zai",
    name: "Z.AI",
    compatibility: "openai",
    defaultModel: "glm-4.7",
    knownModels: ["GLM-5.1", "GLM-5-Turbo", "GLM-5V-Turbo", "glm-4.7", "glm-4.5-air"],
    apiKeyLabel: "API Key",
    apiKeyPlaceholder: "zai-...",
    requiresBaseUrl: true,
    description: "OpenAI-compatible endpoint required.",
  },
  {
    id: "glm",
    name: "GLM",
    compatibility: "openai",
    defaultModel: "glm-4-plus",
    apiKeyLabel: "API Key",
    apiKeyPlaceholder: "glm-...",
    requiresBaseUrl: true,
    description: "OpenAI-compatible endpoint required.",
  },
  {
    id: "vercel-ai-gateway",
    name: "Vercel AI Gateway",
    compatibility: "anthropic",
    baseUrl: "https://ai-gateway.vercel.sh/v1",
    defaultModel: "claude-sonnet-4-6",
    apiKeyLabel: "API Key",
    apiKeyPlaceholder: "vgw_...",
    apiKeyUrl: "https://vercel.com/docs/ai-gateway",
  },
  {
    id: "moonshot",
    name: "Moonshot (Kimi)",
    compatibility: "openai",
    baseUrl: "https://api.moonshot.ai/v1",
    defaultModel: "kimi-k2.5",
    apiKeyLabel: "API Key",
    apiKeyPlaceholder: "sk-...",
  },
  {
    id: "cerebras",
    name: "Cerebras",
    compatibility: "openai",
    baseUrl: "https://api.cerebras.ai/v1",
    defaultModel: "llama3.1-8b",
    apiKeyLabel: "API Key",
    apiKeyPlaceholder: "csk_...",
    apiKeyUrl: "https://cloud.cerebras.ai/",
  },
  {
    id: "mistral",
    name: "Mistral",
    compatibility: "openai",
    baseUrl: "https://api.mistral.ai/v1",
    defaultModel: "mistral-large-latest",
    apiKeyLabel: "API Key",
    apiKeyPlaceholder: "mistral-...",
    apiKeyUrl: "https://console.mistral.ai/",
  },
  {
    id: "github-copilot",
    name: "GitHub Copilot",
    compatibility: "openai",
    defaultModel: "gpt-4o",
    apiKeyLabel: "GitHub Token",
    apiKeyPlaceholder: "ghp_...",
  },
  {
    id: "nano-gpt",
    name: "NanoGPT",
    compatibility: "openai",
    baseUrl: "https://nano-gpt.com/api/v1",
    defaultModel: "minimax/minimax-m2.7",
    knownModels: [
      "minimax/minimax-m2.7",
      "openai/gpt-5.2",
      "google/gemini-3-pro-preview",
      "anthropic/claude-sonnet-4-5",
    ],
    apiKeyLabel: "NanoGPT API Key",
    apiKeyPlaceholder: "nanogpt-...",
    apiKeyUrl: "https://nano-gpt.com/api",
    description: "OpenAI-compatible NanoGPT endpoint with a prefilled base URL.",
  },
  {
    id: "qwen-portal",
    name: "Qwen",
    compatibility: "anthropic",
    baseUrl: "https://portal.qwen.ai/v1",
    defaultModel: "coder-model",
    apiKeyLabel: "API Key / Token",
    apiKeyPlaceholder: "qwen-...",
  },
  {
    id: "minimax",
    name: "MiniMax",
    compatibility: "openai",
    baseUrl: "https://api.minimax.io/v1",
    defaultModel: "MiniMax-M2.1",
    knownModels: [
      "MiniMax-M3",
      "MiniMax-M2.7",
      "MiniMax-M2.7-highspeed",
      "MiniMax-M2.5",
      "MiniMax-M2.5-highspeed",
      "MiniMax-M2.1",
      "MiniMax-M2.1-highspeed",
      "MiniMax-M2",
    ],
    apiKeyLabel: "API Key",
    apiKeyPlaceholder: "minimax-...",
  },
  {
    id: "minimax-portal",
    name: "MiniMax Portal",
    compatibility: "anthropic",
    baseUrl: "https://api.minimax.io/anthropic",
    defaultModel: "MiniMax-M2.1",
    knownModels: [
      "MiniMax-M2.7",
      "MiniMax-M2.7-highspeed",
      "MiniMax-M2.5",
      "MiniMax-M2.5-highspeed",
      "MiniMax-M2.1",
      "MiniMax-M2.1-highspeed",
      "MiniMax-M2",
    ],
    apiKeyLabel: "API Key / Token",
    apiKeyPlaceholder: "minimax-...",
  },
  {
    id: "xiaomi",
    name: "Xiaomi MiMo",
    compatibility: "anthropic",
    baseUrl: "https://api.xiaomimimo.com/anthropic",
    defaultModel: "mimo-v2-flash",
    apiKeyLabel: "API Key",
    apiKeyPlaceholder: "mimo-...",
  },
  {
    id: "venice",
    name: "Venice AI",
    compatibility: "openai",
    baseUrl: "https://api.venice.ai/api/v1",
    defaultModel: "llama-3.3-70b",
    apiKeyLabel: "API Key",
    apiKeyPlaceholder: "venice-...",
  },
  {
    id: "synthetic",
    name: "Synthetic",
    compatibility: "anthropic",
    baseUrl: "https://api.synthetic.new/anthropic",
    defaultModel: "hf:MiniMaxAI/MiniMax-M2.1",
    apiKeyLabel: "API Key",
    apiKeyPlaceholder: "syn_...",
  },
  {
    id: "kimi-code",
    name: "Kimi Code",
    compatibility: "openai",
    baseUrl: "https://api.kimi.com/coding/v1",
    defaultModel: "kimi-for-coding",
    apiKeyLabel: "API Key",
    apiKeyPlaceholder: "sk-...",
  },
  {
    id: "anthropic-compatible",
    name: "Anthropic-Compatible (Custom)",
    compatibility: "anthropic",
    baseUrl: "http://localhost:4000",
    defaultModel: "claude-sonnet-4-6",
    apiKeyLabel: "API Key",
    apiKeyPlaceholder: "sk-...",
    requiresBaseUrl: true,
  },
  {
    id: "hf-agents",
    name: "HuggingFace Local AI",
    compatibility: "openai",
    baseUrl: "http://localhost:8080/v1",
    defaultModel: "auto",
    apiKeyLabel: "API Key (optional)",
    apiKeyPlaceholder: "sk-... (leave empty for local)",
    apiKeyOptional: true,
    description:
      "Run local models via hf-agents + llama.cpp. Inference stays local by default; optional remote services follow their own data policies. Setup: (1) pip install huggingface_hub  (2) hf extensions install hf-agents",
  },
  {
    id: "mlx",
    name: "MLX (Apple Silicon)",
    compatibility: "openai",
    baseUrl: "http://localhost:8080/v1",
    defaultModel: "mlx-community/Qwen3-8B-4bit",
    knownModels: [
      "mlx-community/Qwen3-8B-4bit",
      "mlx-community/Qwen3-14B-4bit",
      "mlx-community/Qwen3-30B-A3B-4bit",
      "mlx-community/Qwen3.6-35B-A3B-4bit-DWQ",
    ],
    apiKeyLabel: "API Key (optional)",
    apiKeyPlaceholder: "Leave empty for local inference",
    apiKeyOptional: true,
    description:
      "Run MLX-LM natively on Apple Silicon through its local OpenAI-compatible server. Setup: pip install mlx-lm",
  },
];

export const CUSTOM_PROVIDER_MAP = new Map<LLMProviderType, ProviderCatalogEntry>(
  CUSTOM_PROVIDER_CATALOG.map((provider) => [provider.id, provider]),
);

export const CUSTOM_PROVIDER_IDS = new Set(CUSTOM_PROVIDER_CATALOG.map((provider) => provider.id));
